Adding statuses to controls.
CivicActions/govready-q pull request #4
Opened 2021-09-27 22:29 UTC by Tom-Camp

This PR adds a Status field to the ElementControl class and an Ajax/JsonResponse for updating the Status field.

Statuses are:

Needs work
Ready for assessment
Assessed
Changes requested

The display for these changes are in the branding PR: https://github.com/CMSgov/rato-grq-branding/pull/14

2021-10-13 15:06 UTC, woodt requested changes
Modulo a minor change, looks OK to me.  Would be nice to have some tests.

2021-10-13 15:06 UTC, woodt commented on controls/views.py
> +        allowed = ["2","3","4","5"]
Can we pull these values out of ElementControl.Statuses so there is only one source of truth about what the allowed values are?

2021-10-14 17:49 UTC, Tom-Camp commented on controls/views.py
> +        allowed = ["2","3","4","5"]
Done and pushed

2021-10-14 18:19 UTC, woodt approved these changes

2021-10-14 18:19 UTC, merged